-- 有异地业务发生，无异地申请 fx_0010
SELECT
A.SETL_ID,
A.PSN_NO
FROM SETLCENT_DB.SETL_D A
WHERE A.VALI_FLAG = '1'
AND A.MED_TYPE LIKE '21%'
AND A.REFD_SETL_FLAG = '0'
AND A.INSU_ADMDVS LIKE '6209%'
AND DATE_FORMAT(A.CRTE_TIME, '%Y%m') = DATE_FORMAT(CURRENT_DATE - '1 MONTH'::INTERVAL, '%Y%m')
AND A.PAY_LOC IN ('4')
-- 凡是酒泉市内参保人前往青海海西州(行政区划: 632800) 跨省就医的，取消异地就医备案的条件判定，酒泉参保人无需异地备案按照本地就医待遇政策在青海所有定点医疗机构就诊结算
AND (CASE WHEN A.INSU_ADMDVS LIKE '6209%' AND A.FIX_BLNG_ADMDVS = '632800' THEN '1' ELSE '0' END ) = '0'
AND NOT EXISTS(SELECT 1 FROM SETLCENT_DB.OUT_APPY_D B WHERE A.PSN_NO = B.PSN_NO)
AND NOT EXISTS(SELECT 1 FROM HIBIZ_DB.OUT_APPY_EVT_C C WHERE A.PSN_NO = C.PSN_NO)
AND NOT EXISTS(SELECT 1 FROM SETLCENT_DB.PSN_FIL_SUM_INFO_D D WHERE A.PSN_NO = D.PSN_NO)
LIMIT 20;

执行无数据