# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_process_tasks_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchProcessTasksDialog(object):
    def setupUi(self, BatchProcessTasksDialog):
        BatchProcessTasksDialog.setObjectName("BatchProcessTasksDialog")
        BatchProcessTasksDialog.resize(431, 352)
        self.gridLayout = QtWidgets.QGridLayout(BatchProcessTasksDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel = QtWidgets.QLabel(BatchProcessTasksDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.titleEdit = QtWidgets.QLineEdit(BatchProcessTasksDialog)
        self.titleEdit.setEnabled(True)
        self.titleEdit.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"color: rgb(120, 120, 120);")
        self.titleEdit.setReadOnly(True)
        self.titleEdit.setObjectName("titleEdit")
        self.gridLayout.addWidget(self.titleEdit, 0, 1, 1, 1)
        self.systemProcessStatusLabel = QtWidgets.QLabel(BatchProcessTasksDialog)
        self.systemProcessStatusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.systemProcessStatusLabel.setObjectName("systemProcessStatusLabel")
        self.gridLayout.addWidget(self.systemProcessStatusLabel, 1, 0, 1, 1)
        self.systemProcessStatusComboBox = QtWidgets.QComboBox(BatchProcessTasksDialog)
        self.systemProcessStatusComboBox.setObjectName("systemProcessStatusComboBox")
        self.systemProcessStatusComboBox.addItem("")
        self.systemProcessStatusComboBox.addItem("")
        self.systemProcessStatusComboBox.addItem("")
        self.systemProcessStatusComboBox.addItem("")
        self.systemProcessStatusComboBox.addItem("")
        self.gridLayout.addWidget(self.systemProcessStatusComboBox, 1, 1, 1, 1)
        self.resultDescLabel = QtWidgets.QLabel(BatchProcessTasksDialog)
        self.resultDescLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resultDescLabel.setObjectName("resultDescLabel")
        self.gridLayout.addWidget(self.resultDescLabel, 2, 0, 1, 1)
        self.resultDescTextEdit = QtWidgets.QTextEdit(BatchProcessTasksDialog)
        self.resultDescTextEdit.setObjectName("resultDescTextEdit")
        self.gridLayout.addWidget(self.resultDescTextEdit, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.acceptedButton = QtWidgets.QPushButton(BatchProcessTasksDialog)
        self.acceptedButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.acceptedButton.setObjectName("acceptedButton")
        self.horizontalLayout.addWidget(self.acceptedButton)
        self.cancelButton = QtWidgets.QPushButton(BatchProcessTasksDialog)
        self.cancelButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)

        self.retranslateUi(BatchProcessTasksDialog)
        QtCore.QMetaObject.connectSlotsByName(BatchProcessTasksDialog)

    def retranslateUi(self, BatchProcessTasksDialog):
        _translate = QtCore.QCoreApplication.translate
        BatchProcessTasksDialog.setWindowTitle(_translate("BatchProcessTasksDialog", "Dialog"))
        self.titleLabel.setText(_translate("BatchProcessTasksDialog", "基金安全主题"))
        self.systemProcessStatusLabel.setText(_translate("BatchProcessTasksDialog", "系统处理状态"))
        self.systemProcessStatusComboBox.setItemText(0, _translate("BatchProcessTasksDialog", "正常"))
        self.systemProcessStatusComboBox.setItemText(1, _translate("BatchProcessTasksDialog", "异常"))
        self.systemProcessStatusComboBox.setItemText(2, _translate("BatchProcessTasksDialog", "可疑"))
        self.systemProcessStatusComboBox.setItemText(3, _translate("BatchProcessTasksDialog", "无法执行"))
        self.systemProcessStatusComboBox.setItemText(4, _translate("BatchProcessTasksDialog", "脚本优化"))
        self.resultDescLabel.setText(_translate("BatchProcessTasksDialog", "检查结果说明"))
        self.acceptedButton.setText(_translate("BatchProcessTasksDialog", "确认"))
        self.cancelButton.setText(_translate("BatchProcessTasksDialog", "取消"))
